SET NAMES 'latin1';
DROP DATABASE IF EXISTS nombres;
CREATE DATABASE IF NOT EXISTS nombres DEFAULT CHARACTER SET utf8;
USE nombres;

CREATE TABLE alumnos(
id_al				INTEGER NOT NULL AUTO_INCREMENT,
nombre				VARCHAR(45) NOT NULL UNIQUE,
PRIMARY KEY (id_al)
)DEFAULT CHARACTER SET utf8;
